### ISSUE TITLE
Is this project still running?

### ISSUE THREAD

**Issue by NigelThorne** [continuoustests/OpenIDE#11]
Hi guys, 

I love the idea of OpenIDE. 
I'm having some trouble getting it working, so I wanted to know if it's worth persevering. 
Is this project ongoing or mothballed? Do the authors still use it themselves?

Cheers
Nigel

**Comment by acken** [comment]
Yes I use it on a daily basis but I am quite certain I'm the only user :)

**Comment by NigelThorne** [comment]
What is your common usage? 
Language? 
Editor?
OS?

Trying to work out what the happy path is. :)

**Comment by acken** [comment]
I am currently using it mainly using vim with tmux on linux. Main in F#, php, C# and golang. However IDE type stuff I mostly use in php and C# as they are the more verbose and annoying languages :) I tend to just extend it with scripts, reactive scripts as I go often being project spesific to automate my flow as much as possible.
